CREATE TABLE EMPLOYEES
(
	ID INT PRIMARY KEY AUTO_INCREMENT,
	FIRST_NAME VARCHAR(35) NOT NULL,
    LAST_NAME VARCHAR(35) NOT NULL,
    DATE_OF_BIRTH DATE NOT NULL,
    DEPARTMENT_ID INT,
    SALARY FLOAT NOT NULL
    

);

INSERT INTO EMPLOYEES
(FIRST_NAME,LAST_NAME,DATE_OF_BIRTH,DEPARTMENT_ID,SALARY)
VALUES
('ALEX','BONNY','1987-02-23',10,4000),
('JOE','MORGAN','1985-03-15',12,6000),
('CHARLES','KIRBY','1989-10-16',10,4500),
('ALEXANDAR','BLINK','1993-06-19',13,7500);



SELECT * FROM EMPLOYEES;







CREATE TABLE DEPARTMENTS
(
	DEPT_ID INT PRIMARY KEY ,
	DEPT_NAME VARCHAR(40) UNIQUE

);

INSERT INTO DEPARTMENTS
(DEPT_ID,DEPT_NAME)
VALUES
(10,'IT'),
(11,'ADVERTISEMENT'),
(12,'SALES AND MARKETING'),
(13,'FINANCE'),
(14,'ACCOUNTS'),
(15,'HRD'),
(16,'MANAGEMENT');


SELECT * FROM DEPARTMENTS
ORDER BY DEPT_ID



