

CREATE DATABASE OFFICE2;
USE OFFICE2;


CREATE TABLE DEPARTMENT
(
    DEPT_ID INT PRIMARY KEY,
    DEPT_NAME VARCHAR(30)
);

INSERT INTO DEPARTMENT
VALUES
(10,'Administration'),
(20,'Marketing'),
(30,'Purchasing'),
(40,'Human Resources'),
(50,'Shipping'),
(60,'IT');
 
CREATE TABLE EMPLOYEE
(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(30),
    EMAIL VARCHAR(40) UNIQUE,
    DEPT_ID INT,
    
    FOREIGN KEY(DEPT_ID) REFERENCES DEPARTMENT(DEPT_ID) ON DELETE SET NULL
);

CREATE TABLE JOB_HISTORY
(
    HISTORY_ID INT PRIMARY KEY,
    EMPLOYEE_ID INT,
    STARTDATE DATE NOT NULL,
    ENDDATE DATE, 
    DEPT_ID INT,
    
    FOREIGN KEY(EMPLOYEE_ID) REFERENCES EMPLOYEE(ID) ON DELETE SET NULL, 
    FOREIGN KEY(DEPT_ID) REFERENCES DEPARTMENT(DEPT_ID) ON DELETE SET NULL
);

INSERT INTO EMPLOYEE(NAME,EMAIL,DEPT_ID)
VALUES
('Sadek','sadek@gmail',20),
('Mynul','mynul@gmail',10),
('Asif','asif@gmail',40),
('Sakib','sakib@gmail',30),
('Aziz','aziz@gmail',50),
('Tasnim','tasnim@gmail',60);

INSERT INTO JOB_HISTORY
VALUES
(1,2,'2022-03-05','2023-01-05',10),
(2,4,'2022-04-05','2023-04-05',30),
(3,5,'2022-05-05','2023-02-05',50);



INSERT INTO JOB_HISTORY
VALUES
(4,2,'2022-05-05','2023-02-05',50);

SELECT * FROM EMPLOYEE;

DELETE FROM department
WHERE dept_id = 10;
use office2;

select * from job_history;
