-- CONCEPTUAL SESSION 2-1


-- PROBLEM 1 : FIND THE EMPLOYEES WHO'S SALARY IS
-- GREATER THAN THE AVERAGE SALARY OF ALL EMPLOYEES
/*
SELECT FIRST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY > (SELECT AVG(SALARY)
FROM EMPLOYEES);

*/



/*
-- PROBLEM 2: FIND EMPLOYEES WHO'S SALARY IS GREATER 
-- THANK STEVEN'S.

SELECT * 
FROM EMPLOYEES
WHERE SALARY > (SELECT SALARY
				FROM EMPLOYEES 
				WHERE FIRST_NAME = 'STEVEN' AND LAST_NAME = 'KING'
				)

*/




/*
-- PROBLEM 3 : FIND THE HIGHEST SALARY IN 
-- EACH DEPARTMENT AND WHO GETS IT

SELECT FIRST_NAME,SALARY,DEPARTMENT_ID 
FROM EMPLOYEES 
WHERE(SALARY,DEPARTMENT_ID) IN (SELECT MAX(SALARY),DEPARTMENT_ID
								FROM EMPLOYEES 
								GROUP BY DEPARTMENT_ID)
ORDER BY DEPARTMENT_ID

*/